services:
  db:
    image: postgres:latest
    restart: always
    env_file: ./.env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    restart: always
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
